version: "3.8"
services:
  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER = "${POSTGRES_USER}"
      - POSTGRES_PASSWORD = "${POSTGRES_PASSWORD}"
      - POSTGRES_DB = "${POSTGRES_DB}"
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
      args:
        - VITE_BACKEND_PORT = "${VITE_BACKEND_PORT}"
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${VITE_BACKEND_PORT}:${VITE_BACKEND_PORT}"
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  pgdata:
